url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Genomes of Luminous Organisms
email: dschultz@mbari.org
description: "This is the future website of the Genomes of Luminous Organisms Project. We hope to sequence luminous organisms spanning the tree of life to elucidate their evolution and create new molecular tools for scientists."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Darrin Schultz
  pic: darrin
  position: Male Model
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Dr. Steve Haddock
  pic: steve
  position: Muse
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Lynne Christianson
  pic: lynne
  position: Rockstar/CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Monterey Bay Aquarium Research Institute
  - line: 7700 Sandholdt Road
  - line: Moss Landing, CA 95039

# Build settings
markdown: kramdown
permalink: pretty