# Site wide configuration

title: "glo"
description: "Genomes of Luminous Organisms"
logo: glo_120px.jpg
teaser: test_header.gif
locale: en
url:
feed:
  path: atom.xml

excerpt_separator: "o87q23ljbszhmbsdfmjxjryw3isdufhzcx,jehjzhdf,uih" 
# Members info

groups:
- name: Project Coordinators
  people:
  - name: Darrin Schultz
    pic: darrin.jpg
    position: PhD Student
    social:
      - title: twitter
        url: twitter.com
      - title: facebook
        url: facebook.com
      - title: stack-overflow
        url: stack-overflow.com

  - name: Steve Haddock
    pic: steve.jpg
    position: PI
    social:
      - title: twitter
        url: twitter.com
      - title: facebook
        url: facebook.com
      - title: stack-overflow
        url: stack-overflow.com

- name: Contributors
  people:
  - name: Warren Francis
    pic: warren.jpg
    position: Bioinformatician at LMUM
    social:
      - title: twitter
        url: twitter.com
      - title: facebook
        url: facebook.com
      - title: stack-overflow
        url: stack-overflow.com

  - name: Lynne Christianson
    pic: lynne.jpg
    position: Haddock Lab Technician
    social:
      - title: twitter
        url: twitter.com
      - title: facebook
        url: facebook.com
      - title: stack-overflow
        url: stack-overflow.com

  - name: Yuichi Oba
    pic: oba.jpg
    position: PI at Chubu University
    social:
      - title: bug
        url: http://www3.chubu.ac.jp/faculty/oba_yuichi/English/

  - name: Ilia Yampolsky
    pic: ilia.jpg
    position: PI at IBCh-RAS
    social:
      - title: bug
        url: http://www3.chubu.ac.jp/faculty/oba_yuichi/English/

  - name: Joseph Ryan
    pic: joe_ryan.jpg
    position: PI
    social:
      - title: twitter
        url: twitter.com



# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name:
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values: 
      author_profile: true

include:
  - .htaccess
  - "_pages"

exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
